### ISSUE TITLE
Staking Theta on Guardian Node from Ledger.

### ISSUE THREAD

**Issue by rumiholdingsllc** [TheGPooL/Guides#1]
Receiving "review trans that gives an address I don't recognize. It says data present, amount ETH, max fees ETH - accept and send. This step is not detailed in the GPool/Guides. Therefore I'm reluctant to accept and send?

**Comment by TheGPooL** [comment]
This is a bug with your hardware wallet, please reach out to their support we can not fix this.

**Comment by avatarsatosh** [comment]
> 
> 
> Receiving "review trans that gives an address I don't recognize. It says data present, amount ETH, max fees ETH - accept and send. This step is not detailed in the GPool/Guides. Therefore I'm reluctant to accept and send?

That is a bug from your end ,write the theta customer service on telegram via https://t.me/thetacustomerservice to get it fixed.
