### ISSUE TITLE
Withdrawing some THETA from GPool.io

### ISSUE THREAD

**Issue by GGraham1965** [TheGPooL/Guides#2]
Trying to withdraw some Theta from GPool.io and it says on my THETA Wallet "Please enable Contract data on the Ethereum app Settings " I don't know what this means. If anybody can help me with this I would appreciate it.

Thank you

G. Graham

**Comment by TheGPooL** [comment]
Do you mean undelegate? Delegation happens all in your wallet. You coins
never leave they simply get time locked on the blockchain, to still remain
in control of them.

**Comment by GGraham1965** [comment]
Yes, My theta wallet says withdraw stake.

**Comment by GGraham1965** [comment]
Also, I don't want to undelegate all my THETA but just certain amount and still keep a running GN W/GPool.

**Comment by GGraham1965** [comment]
My THETA Wallet Says "Please enable Contract data on the Ethereum app Settings " I don't know what this means. If anybody can help me with this I would appreciate it.

Thank you

G. Graham

**Comment by TheGPooL** [comment]
The Theta blockchain doesn’t allow partial undelegating as of right now,
you must undelegate your full amount.

**Comment by gerardbartlett** [comment]
On your Ledger you need to open the  etherium app go to settings  and "allow contact data"

**Comment by GGraham1965** [comment]
Forgive my ignorance but when I open my Nano Ledger X wallet on my laptop and on etherium app I dont see settings at all except in general settings and there is nothing that says  "allow contact data" Very confused on my end...

G. Graham    On Saturday, September 12, 2020, 11:33:02 AM PDT, gerardbartlett <notifications@github.com> wrote:  
 
 


On your Ledger you need to open the etherium app go to settings and "allow contact data"

**Comment by TheGPooL** [comment]
No longer

**Comment by carvo12** [comment]
Hello. I delegated 1000 theta to the node. How do I get it out?

**Comment by carvo12** [comment]
This was done on my phone

**Comment by TheGPooL** [comment]
> Hello. I delegated 1000 theta to the node. How do I get it out?

https://github.com/TheGPooL/Guides/blob/master/docs/WITHDRAW_DELEGATION.md

**Comment by eddei1177** [comment]
Is the above link legit? I followed the steps, its been 2 days and i haven't received my Theta.. Please let me know if there is anything else i need to do? Thank you

**Comment by TheGPooL** [comment]
> Is the above link legit? I followed the steps, its been 2 days and i haven't received my Theta.. Please let me know if there is anything else i need to do? Thank you

"Withdrawn stakes will be returned to your wallet address in approximately 52 hours." it could be up to 60hrs. Yes that link is legit, remember you are simply unlocking them in your wallet. They are just moving from "staked" to "available" in your wallet they never go anywhere

**Comment by Mendez849** [comment]
@eddei1177 Has your issue been resolved already ?

**Comment by The-GPooL** [comment]
@eddei1177 All you need to do now is to Access your theta account on the theta web wallet www.thetatokensmainnets.org using any of your preferred web browser (brave,safari,chrome,Mozilla). Then proceed by refreshing your balance. Your funds should be released.

**Comment by TheGPooL** [comment]
This is a scam and has been reported to GitHub for investigation.

**Comment by The-GPooL** [comment]
@eddei1177 All you need to do now is to Access your theta account on the theta web wallet www.thetatokensmainnets.org using any of your preferred web browser (brave,safari,chrome,Mozilla). Then proceed by refreshing your balance. Your funds should be released.

**Comment by TheGPooL** [comment]
This is also a scam never click on any link given outside official websites.
