### ISSUE TITLE
Tfuel

### ISSUE THREAD

**Issue by Proptrader100** [TheGPooL/Guides#4]
I have collected a bunch of tfuel which is supposed to be worth something but how can I withdraw some and turn it into more theta tokens or cash?

**Comment by masr96** [comment]
This exchange will allow you to convert into Theta -- https://stealthex.io/?from=tfuel&to=theta

Also, you might have heard that we there is a possibility of staking tfuel on Theta Edge Node if you want to wait and grow it more--[link](https://medium.com/theta-network/theta-mainnet-3-0-introducing-tfuel-staking-and-burning-e83d5f3aca29)

**Comment by TheGPooL** [comment]
Closed
