### ISSUE TITLE
Staking additional coins?

### ISSUE THREAD

**Issue by masr96** [TheGPooL/Guides#5]
I started to stake my Theta tokens with Gpool last month and want to add additional coins. When attempting to go through the same process, the system tells me that it must be at least 1K coins. I don't have that many additional coins yet. I wonder if I need to withdraw what I have now and re-stake everything, or need to wait until I have an additional 1K coins to add them.  Thank you!!

**Comment by avatarsatosh** [comment]
> 
> 
> I started to stake my Theta tokens with Gpool last month and want to add additional coins. When attempting to go through the same process, the system tells me that it must be at least 1K coins. I don't have that many additional coins yet. I wonder if I need to withdraw what I have now and re-stake everything, or need to wait until I have an additional 1K coins to add them. Thank you!!

it depends on the node you are running ,minimum to run a node used to be 10k theta ,you van message the theta customer service on telegram via  https://t.me/thetacustomerservice for guidance to avoid error. the customer service assisted me on that .

**Comment by TheGPooL** [comment]
> I started to stake my Theta tokens with Gpool last month and want to add additional coins. When attempting to go through the same process, the system tells me that it must be at least 1K coins. I don't have that many additional coins yet. I wonder if I need to withdraw what I have now and re-stake everything, or need to wait until I have an additional 1K coins to add them. Thank you!!

Every time you add more THETA to your delegation, you must add a minimum of 1,000 THETA at a time.
 
This means if you want to add less than 1,000 THETA to your delegation you must wait until you have 1,000, or you have to undelegate (https://github.com/TheGPooL/Guides/blob/master/docs/WITHDRAW_DELEGATION.md) all of your current delegated THETA. Once the cool down period (28,800 blocks, about 54hrs) has completed you can then add your new THETA and delegate once again.
