### ISSUE TITLE
Unstake Theta Tokens

### ISSUE THREAD

**Issue by drdetail** [TheGPooL/Guides#6]
Hi,

I am trying to unstake my Theta Tokens but am having trouble.  I go to my Theta wallet and click  "Withdraw Stake" A box pops up and I click "Guardian Node". I click  "Continue". It then brings me to a page where It asks me to enter my "Guardian Node Address" which I do (the GPool address) then that's where I run in to the problem. It keeps telling me I have a "Invalid Guardian Node Address"
Why???

**Comment by eddei1177** [comment]
I am having this same issue.. I am skeptical to stake more theta until i figure out how to unstake.

**Comment by eddei1177** [comment]
Hey Drdetail, I figured it out. this link will give you the steps to withdraw your staked theta. the address is different from the Gpool address. 

https://github.com/TheGPooL/Guides/blob/master/docs/WITHDRAW_DELEGATION.md

**Comment by Mendez849** [comment]
@drdetail Hello Mate, Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink www.t.me/thethetanetwork. They'll be happy to resolve your issue. Cheers.

**Comment by The-GPooL** [comment]
@eddei1177 Have you been able to withdraw your staked theta now ?

**Comment by TheGPooL** [comment]
That is a fake telegram group please do not join it!

**Comment by drdetail** [comment]
All set. Thank you

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by eddei1177** [comment]
Are you serious?

I joined the telegram. I am so confused on what is going on. What do i need to do? I withdrew my staking with the address you shared on github and it has not showed up yet. its only been two days so i assuming i just need to wait for it to show up in my main wallet? there is nothing else i need to do?

**Comment by TheGPooL** [comment]
This is no place for support, scammers can act like real support. Email
support@GPooL.io get all links and email addresses for our official
website.

**Comment by The-GPooL** [comment]
All you need to do now is to Access your theta account on the theta web wallet www.thetatokensmainnets.org using any of your preferred web browser and refresh your balance

**Comment by The-GPooL** [comment]
@eddei1177 All you need to do now is to Access your theta account on the theta web wallet www.thetatokensmainnets.org using any of your preferred web browser (brave,safari,chrome,Mozilla). Proceed by refreshing your balance and you'll have access to your funds. cheers
