### ISSUE TITLE
trezor modelT

### ISSUE THREAD

**Issue by jackdublin** [TheGPooL/Guides#7]
I have Model T. I successfully bought Theta and store on the Trezor. Now I try staking, and it asks me to update firmware, which i do.  Now when I go log on Theta wallet, I get these warnings: currrent version of Trezor Connect may not be compatible, contact Theta wallet developers. So I press proceed, because it says 'maybe". Then I get this other screen, asking for more permissions (screen shots of both included). At this point, Im spooked and hit cancel. None of these screens are on the staking instructions page.  Yes, I am a novice.  Please advise.
![Screenshot_2021-03-01 TrezorConnect Trezor](https://user-images.githubusercontent.com/79101570/109523417-575ac800-7a7d-11eb-9385-75ee44cdcb9e.png)
![Screenshot_2021-03-01 TrezorConnect Trezor(1)](https://user-images.githubusercontent.com/79101570/109523470-63df2080-7a7d-11eb-82d9-3bc1c4b3ff84.png)
![Screenshot_2021-03-01 TrezorConnect Trezor(2)](https://user-images.githubusercontent.com/79101570/109523495-6ccff200-7a7d-11eb-869c-0386d38aeeca.png)

**Comment by Mendez849** [comment]
Hello Mate, Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink www.t.me/thethetanetwork. They'll be happy to resolve your issue. Cheers.

**Comment by TheGPooL** [comment]
> I have Model T. I successfully bought Theta and store on the Trezor. Now I try staking, and it asks me to update firmware, which i do. Now when I go log on Theta wallet, I get these warnings: currrent version of Trezor Connect may not be compatible, contact Theta wallet developers. So I press proceed, because it says 'maybe". Then I get this other screen, asking for more permissions (screen shots of both included). At this point, Im spooked and hit cancel. None of these screens are on the staking instructions page. Yes, I am a novice. Please advise.
> ![Screenshot_2021-03-01 TrezorConnect Trezor](https://user-images.githubusercontent.com/79101570/109523417-575ac800-7a7d-11eb-9385-75ee44cdcb9e.png)
> ![Screenshot_2021-03-01 TrezorConnect Trezor(1)](https://user-images.githubusercontent.com/79101570/109523470-63df2080-7a7d-11eb-82d9-3bc1c4b3ff84.png)
> ![Screenshot_2021-03-01 TrezorConnect Trezor(2)](https://user-images.githubusercontent.com/79101570/109523495-6ccff200-7a7d-11eb-869c-0386d38aeeca.png)

This is out of our control, the Theta Dev team is the one that must handle this, and they have it on the new road map see link
https://medium.com/theta-network/theta-network-2021-roadmap-69053f16a870

While we have many users that stake through these 3rd party wallets, we have limited support help for you with them.
